version: '3.1'
services:
  mysql:
    image: mysql:8.0.18
    restart: always
    expose:
      - '3306'
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./initial:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: "appuser"
      MYSQL_DATABASE: "mysqldb"
      MYSQL_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "password"